### ISSUE TITLE
re: booltron on blender contrib

### ISSUE THREAD

**Issue by meta-androcto** [mrachinskiy/blender-addon-booltron#2]
hi, I would like to put booltron in blender contrib, is this ok with you?

**Comment by mrachinskiy** [comment]
Hi, I think my add-on has too specific feature set aimed for jewelry and product design and might not be as great for animation or game dev, and contrib already includes “Boolean Operators”. 

“BoolTool” (currently included in external) is much better choice for contrib and already quite popular. If you decide to include it, please remove “Boolean Operators”, having two add-ons in contrib doing exact same thing is not very pretty.

**Comment by meta-androcto** [comment]
Hi, yes booltools has more options & would be a good inclusion.
Booltron has extra function "Separate" & would make a good replacement for "Boolean Operators"
I think it's worth the change, I'll give it a go next few days, Already started by making it one file, just need to do code cleanup & some ui/hotkey things & should be good. 
Thanks.

**Comment by mrachinskiy** [comment]
Then “[Sculpt Tools](https://github.com/MadMinstrel/blender-sculpt-tools)” has more features to offer along with Separate it also has Clone boolean tool.

What so specific about my add-on that you wish to bundle it with Blender?

**Comment by meta-androcto** [comment]
nothing so specific, just so similar to boolean operators, I saw the similarity & thought it would be better to use your version given the extra function. Taking the script to it's logical conclude. :)

**Comment by mrachinskiy** [comment]
As I understand contrib version of this add-on is not going to be maintained by me, then let me change the name and identifiers of the add-on to something like “Extra Boolean Tools” so there would not be any confusion or conflicts.
Send an email to mikhail.rachinskiy@gmail.com and I will reply with the altered version.

**Comment by meta-androcto** [comment]
hi, your quite welcome to continue maintaining the addon, just create a task here: https://developer.blender.org/maniphest/project/3/type/Patch/ when ever you update & I'll pick it up
here's the version I put in one script & renamed slightly: 
[bool_up.zip](https://github.com/mrachinskiy/blender-addon-booltron/files/240946/bool_up.zip)
It's by no means tidy up properly, I don't really see much maintain on this unless your adding new features or api change fixes. Name is not important, I would replace boolean operators with booltron code & keep the name & hotkey from boolean operators addon. the author is ok with me doing this.
Thanks again, my email is swamped, best to contact me here.

**Comment by mrachinskiy** [comment]
I like how you called the add-on, “Bool Up” is an ideal name for it—clean and catchy. “Boolean Operators” made me fall asleep every time I read it.

Here is stripped down version [bool_up.zip](https://github.com/mrachinskiy/blender-addon-booltron/files/241179/bool_up.zip), I deleted all jewelry design specific functionality and keymaps (they are really useless for this kind of add-on), now there is only pure generic boolean toolset.

Only two things are missing: _wiki_url_ and _tracker_url_.
Could you please create wiki page and specify it in the add-on.
Same for tracker_url, please create archived task in developers.blender.org, make me subscriber ([here is my account](https://developer.blender.org/p/alm/)) and specify it in the add-on as you did with “Boolean Operators”.
Thank you.
